[package]
name = "jan-js-lib-from-rust"
version = "0.1.0"
authors = ["masaue <masayuki.uegaki@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
